apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nginx
        image: elizabethhuang/laravel13-nginx:1.0
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources: {}
        restartPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 80
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 8080
      initContainers:
      - name: php-fpm
        image: elizabethhuang/laravel13:1.0
        ports:
        - containerPort: 9000
        restartPolicy: Always
        startupProbe:
          tcpSocket:
            port: 9000
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000"
        envFrom:
          - secretRef:
              name: api
          - configMapRef:
              name: api
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pwd
                key: PASSWORD
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
