apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-api
  name: deploy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: deploy-api
    spec:
      containers:
      - name: nginx
        image: elizabethhuang/nginx
        ports:
        - containerPort: 80
        resources: {}
        restartPolicy: Always
      initContainers:
      - name: php-fpm
        image: elizabethhuang/laravel51
        ports:
        - containerPort: 9000
        restartPolicy: Always
        livenessProbe:
          httpGet:
            path: /health/liveness
        readinessProbe:
          httpGet:
            path: /health/readiness
        env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: secret-api
                key: APP_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-api
                key: DB_PASSWORD
status: {}
