apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:18
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgres
        env:
        - name: POSTGRES_DB
          value: "laravel"
        - name: POSTGRES_USER
          value: "root"
        - name: TZ
          value: "Asia/Taipei"
        - name: PGTZ
          value: "Asia/Taipei"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pwd
              key: PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
status:
  loadBalancer: {}
